### ISSUE TITLE
signature ontology

### ISSUE THREAD

**Issue by bourgeoa** [0l5en/pod-chat-client#14]
As predicate your app uses a proprietary `https;//www.podchat.com/signature`
You may consider using this ontology `https://w3id.org/security#proof`
see https://github.com/SolidOS/chat-pane/issues/90#issuecomment-1464627273

**Comment by 0l5en** [comment]
To remain backward compatible, the old predicate is still supported. The adjustments from [#10](https://github.com/0l5en/pod-chat-client/issues/10) will be released together with this ticket. The signature generation method used in [#10](https://github.com/0l5en/pod-chat-client/issues/10) already stores the result under the new predicate.
