### ISSUE TITLE
verification consideration

### ISSUE THREAD

**Issue by bourgeoa** [0l5en/pod-chat-client#2]
@Otto-AA made these comments in the forum https://forum.solidproject.org/t/update-pod-chat-messenger-2-0-solid-pod-messaging-app/6141/13?u=bourgeoa

> I have some remarks regarding the verification implementation and also general problem regarding verification. As far as I can tell from the following piece of code there are some possible issues, depending on the rest of the application and some RDF details I’m not sure of.

[github.com](https://github.com/0l5en/pod-chat-client/blob/8cc270e30f3b8d39eb3fb68085902808a36205a9/src/store/solid/Message.ts#L286-L293)
[0l5en/pod-chat-client/blob/8cc270e30f3b8d39eb3fb68085902808a36205a9/src/store/solid/Message.ts#L286-L293](https://github.com/0l5en/pod-chat-client/blob/8cc270e30f3b8d39eb3fb68085902808a36205a9/src/store/solid/Message.ts#L286-L293)
```
const verifySignedMessageContent = async (messages: ChatMessage[], resourceUrl: string): Promise<ChatMessage[]> => {
    const verificationResults = await Promise.all(messages.reduce((acc, message) => {
        const signature = extractObjectLastValue(rdfStore, message.id, resourceUrl, rdfStore.cache.sym(PODCHAT.signature));
        if (signature) {
            return [...acc, verifyMessage(message.maker, message.id, message.content, signature)];
        }
        return acc;
    }, [] as Array<Promise<{ messageId: string, trusted: boolean }>>));
```

> Replay attacks
A malicious person simply resends (copies) a valid message with the same values (same maker, id, content and signature) to the same or a different chat. This message will still be valid. A classic example would be:

> 
> Alice writes to her bank: (“Alice sends Eve 1000€”, signature)
Eve copies the same message: (“Alice sends Eve 1000€”, signature)
The bank sends 2000€ to Eve now, both signatures are valid

> To prevent that you need to make sure that all messages are only considered once and duplicates are rejected. For instance, check if the message id exists twice.

> Forwarding attacks
Similar to the replay attack, a malicious person could copy a valid message and in this case forward it to a different recipient. Depending on how the message id is handled this would still be considered valid (I’m not sure if the message id implicitly specifies and validates the recipient, as the target chat is probably contained in the url).

> Alice writes to her bank Bank1: (“Alice sends Eve 1000€”, signature)
Eve copies the message to Bank2: (“Alice sends Eve 1000€”, signature)
Both Bank1 and Bank2 will think the message is valid and send Eve in total 2000€

> To prevent this, the recipient should be in the verification data (similar to the maker now).

> Impersonation
A malicious person could create a profile with the same profile picture and name as Alice, but a different web id. If they now send a message it will look like Alice send a message. Verification still succeeds, as it thinks they are completely different users.

> Not sure how to prevent this, I guess only by trusting the people which are invited in the chat. But if you trust them, then why do we need to verify the messages in the first place?

> Denial of Service
A malicious person could delay verifySignedMessageContent or make it error, which makes it impossible for other users to see messages or any verification result (depending on the rest of the app implementation). To delay it, simply create a really slow response for the public key on the own server. To make it error, maybe return 403 (not sure if this really errors) or invalid base64 for the signature. Because it uses Promise.all it will wait for all and fail if at least one of the verifications fails.

>
> To prevent it, (1) consider to decouple message loading from verifying messages (so the user can read them even if verification is not finished, with a proper “loading verification” UI), and (2) let each message be verified independent of the results of the others (it should succeed without waiting for others).

**Comment by 0l5en** [comment]
I have created two new issues for the implementation.
https://github.com/0l5en/pod-chat-client/issues/10
https://github.com/0l5en/pod-chat-client/issues/11
