### ISSUE TITLE
Chat in a different folder than pod-chat.com fails to load

### ISSUE THREAD

**Issue by mrkvon** [0l5en/pod-chat-client#43]
## Expected behavior

App can display any chat, as long as it is correctly structured and referenced in `privateTypeIndex`.

## Actual behavior

If we have a chat in other folder than `/pod-chat.com/`, the app discovers it correctly through type index, but it doesn't display it. It seems that currently, the app makes an assumption that all chats live in `/pod-chat.com/`.

It might be that URL of the chat references only chat's uuid, not the folder. The app then tries to find the chat in incorrect folder, and chat is thus not displayed.

**Comment by bourgeoa** [comment]
The actual situation is described here https://github.com/0l5en/pod-chat-client/issues/6
I think the app should declare in `privateTypeIndex` : 
- something different than `longChat` but something else may be `podChat`
- and should use the `solid:container` predicate to declare the pod-chat.com folder and not the subfolder chat

**Comment by bourgeoa** [comment]
The actual way of doing raise also an issue in the your Stuff displayed in the `profile/card#me`

**Comment by 0l5en** [comment]
> It might be that URL of the chat references only chat's uuid, not the folder. The app then tries to find the chat in incorrect folder, and chat is thus not displayed.

That is correct. The full URI to the chat must be used as the URL path parameter instead of just the chat's uuid.
